package org.akropon.appchecker.plugin_ui;

import org.openide.util.NbPreferences;

/**
 * Represents settings panel in options.
 * 
 * U can find options in Tools->Options->Miscellaneous->AppChecker
 * 
 * @author akropon
 */
public final class AppCheckerPanel extends javax.swing.JPanel {

	private final AppCheckerOptionsPanelController controller;
	
	public static final String KEY_BOOLEANVALUE1 = "booleanvalue1";
	public static final String KEY_BOOLEANVALUE2 = "booleanvalue2";
	public static final String KEY_STRINGVALUE = "stringvalue";
	public static final boolean DEF_BOOLEANVALUE1 = false;
	public static final boolean DEF_BOOLEANVALUE2 = false;
	public static final String DEF_STRINGVALUE = "appchecker";

	AppCheckerPanel(AppCheckerOptionsPanelController controller) {
		this.controller = controller;
		initComponents();
		// TODO listen to changes in form fields and call controller.changed()
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        chbx_first = new javax.swing.JCheckBox();
        chbx_second = new javax.swing.JCheckBox();
        txtbx = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(AppCheckerPanel.class, "AppCheckerPanel.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(AppCheckerPanel.class, "AppCheckerPanel.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(AppCheckerPanel.class, "AppCheckerPanel.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(chbx_first, org.openide.util.NbBundle.getMessage(AppCheckerPanel.class, "AppCheckerPanel.text")); // NOI18N
        chbx_first.setName(""); // NOI18N
        chbx_first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbx_firstActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(chbx_second, org.openide.util.NbBundle.getMessage(AppCheckerPanel.class, "AppCheckerPanel.chbx_second.text")); // NOI18N

        txtbx.setText(org.openide.util.NbBundle.getMessage(AppCheckerPanel.class, "AppCheckerPanel.txtbx.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chbx_first)
                            .addComponent(chbx_second))
                        .addGap(0, 82, Short.MAX_VALUE))
                    .addComponent(txtbx))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(chbx_first)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chbx_second)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chbx_firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbx_firstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbx_firstActionPerformed

	void load() {
		chbx_first.setSelected(NbPreferences.forModule(AppCheckerPanel.class).getBoolean(
				KEY_BOOLEANVALUE1, DEF_BOOLEANVALUE1));
		chbx_second.setSelected(NbPreferences.forModule(AppCheckerPanel.class).getBoolean(
				KEY_BOOLEANVALUE2, DEF_BOOLEANVALUE2));
		txtbx.setText(NbPreferences.forModule(AppCheckerPanel.class).get(
				KEY_STRINGVALUE, DEF_STRINGVALUE));
	}

	void store() {
		NbPreferences.forModule(AppCheckerPanel.class).putBoolean(
				KEY_BOOLEANVALUE1, chbx_first.isSelected());
		NbPreferences.forModule(AppCheckerPanel.class).putBoolean(
				KEY_BOOLEANVALUE2, chbx_second.isSelected());
		NbPreferences.forModule(AppCheckerPanel.class).put(
				KEY_STRINGVALUE, txtbx.getText());
	}

	boolean valid() {
		// TODO check whether form is consistent and complete
		return true;
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chbx_first;
    private javax.swing.JCheckBox chbx_second;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField txtbx;
    // End of variables declaration//GEN-END:variables
}
